In [1]:

import pandas as pd

import requests




# Replace 'YOUR_API_KEY' with your actual API key

api_key = '7c17a88e84044c12d66273dfaed7fa39fc15b39d'




# Define the API endpoint you want to query

endpoint = 'https://api.census.gov/data/2019/abscs?get=NAME,GEO_ID,RCPSZFI,NAICS2017_LABEL,ETH_GROUP,SEX,EMPSZFI,EMP,FIRMPDEMP&for=metropolitan%20statistical%20area/micropolitan%20statistical%20area:45300&NAICS2017=00'



# Define the parameters for your query




# Send the request to the API and store the response

response = requests.get(endpoint)




# Convert the response into a pandas DataFrame

df = pd.DataFrame.from_records(response.json()[1:], columns=response.json()[0])




# Save the DataFrame to a CSV file

df.to_csv('../assessment_8/data/census_data_tampa.csv', index=False)

In [2]:
census_tampa = pd.read_csv('../assessment_8/data/census_data_tampa.csv')
census_tampa

,NAME,GEO_ID,RCPSZFI,NAICS2017_LABEL,ETH_GROUP,SEX,EMPSZFI,EMP,FIRMPDEMP,NAICS2017,metropolitan statistical area/micropolitan statistical area
0,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,Total for all sectors,1,1,1,1147469,64459,0,45300
1,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,Total for all sectors,1,1,611,0,8638,0,45300
2,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,Total for all sectors,1,1,612,60909,32788,0,45300
3,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,Total for all sectors,1,1,620,59736,9108,0,45300
4,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,Total for all sectors,1,1,630,69697,5221,0,45300
...,...,...,...,...,...,...,...,...,...,...,...
136,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,531,Total for all sectors,29,1,1,45859,8022,0,45300
137,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,532,Total for all sectors,29,1,1,374362,14129,0,45300
138,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,Total for all sectors,29,2,1,71536,11806,0,45300
139,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,Total for all sectors,29,3,1,354299,34621,0,45300
140,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,Total for all sectors,29,4,1,56741,7921,0,45300

In [3]:
one = census_tampa.rename(columns={'NAME':'Municipality', 'RCPSZFI': 'Firm_Sale_Amount', 'ETH_GROUP' : 'Ethnicity', 'SEX': 'Gender',
'EMPSZFI': 'Firm_Employee_Size', 'EMP': 'Employee_Amount', 'FIRMPDEMP': 'Amount_of_Firms'})




two = one.drop(['NAICS2017_LABEL', 'NAICS2017', 'metropolitan statistical area/micropolitan statistical area', 'Firm_Employee_Size'], axis=1)

two

,Municipality,GEO_ID,Firm_Sale_Amount,Ethnicity,Gender,Employee_Amount,Amount_of_Firms
0,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,1,1,1147469,64459
1,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,1,1,0,8638
2,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,1,1,60909,32788
3,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,1,1,59736,9108
4,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,1,1,69697,5221
...,...,...,...,...,...,...,...
136,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,531,29,1,45859,8022
137,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,532,29,1,374362,14129
138,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,29,2,71536,11806
139,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,29,3,354299,34621
140,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,29,4,56741,7921

In [4]:
new = two.loc[:,'Firm_Sale_Amount'] = two['Firm_Sale_Amount'].astype(str).replace({'511': 'Less than $5,000', '518': '$5,000,$9,000', '531': '$500,000-$999,999', '519' : ' $10,000-$24,999', '521': '$25,000-$49,999', '522' : '$50,000-$99,999', '523': '$100,000-$249,999',

'525': '$250,000 to $499,999', '532': ' $1,000,000 or more' })
two

,Municipality,GEO_ID,Firm_Sale_Amount,Ethnicity,Gender,Employee_Amount,Amount_of_Firms
0,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,1,1,1147469,64459
1,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,1,1,0,8638
2,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,1,1,60909,32788
3,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,1,1,59736,9108
4,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,1,1,69697,5221
...,...,...,...,...,...,...,...
136,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$500,000-$999,999",29,1,45859,8022
137,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$1,000,000 or more",29,1,374362,14129
138,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,29,2,71536,11806
139,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,29,3,354299,34621
140,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,1,29,4,56741,7921

In [5]:
three = (two

.replace({'Gender':{1: 'Total'}})

.replace({'Gender':{2: 'Female'}})

.replace({'Gender':{3: 'Male'}})

.replace({'Gender':{4: 'Equally male/female'}})

.replace({'Gender':{96: 'Classified'}})

.replace({'Gender':{98: 'Unclassificable'}})

.replace({'Ethnicity':{ 1 : 'Total'}})

.replace({'Ethnicity':{20: 'Hispanic'}})

.replace({'Ethnicity':{28: 'Equally Hispanic/non-Hispanic'}})

.replace({'Ethnicity':{29: 'Non-Hispanic'}})

.replace({'Ethnicity':{96: 'Classifiable'}})

.replace({'Ethnicity':{98: 'Unclassifiable'}})

)

In [6]:
final_tampa = three.drop(three[three['Firm_Sale_Amount'] == '1'].index)

final_tampa.to_csv('../assessment_8/data/census_data_draft.csv', index=False)

In [8]:
final_tampa['State'] = pd.Series(['Florida']*139)
pd.options.display.max_rows = 999
final_tampa

,Municipality,GEO_ID,Firm_Sale_Amount,Ethnicity,Gender,Employee_Amount,Amount_of_Firms,State
10,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"Less than $5,000",Total,Total,946,527,Florida
11,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$5,000,$9,000",Total,Total,312,554,Florida
12,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$10,000-$24,999",Total,Total,1436,1444,Florida
13,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$25,000-$49,999",Total,Total,2832,2903,Florida
14,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$50,000-$99,999",Total,Total,7682,6562,Florida
15,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$100,000-$249,999",Total,Total,24545,13107,Florida
16,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$250,000 to $499,999",Total,Total,35532,11657,Florida
17,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$500,000-$999,999",Total,Total,54755,9591,Florida
18,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$1,000,000 or more",Total,Total,1019429,18114,Florida
29,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"Less than $5,000",Total,Female,0,0,Florida
30,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$5,000,$9,000",Total,Female,0,0,Florida
31,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$10,000-$24,999",Total,Female,0,0,Florida
32,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$25,000-$49,999",Total,Female,519,836,Florida
33,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$50,000-$99,999",Total,Female,2474,1765,Florida
34,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$100,000-$249,999",Total,Female,6169,3315,Florida
35,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$250,000 to $499,999",Total,Female,10277,2583,Florida
36,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$500,000-$999,999",Total,Female,11229,1987,Florida
37,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$1,000,000 or more",Total,Female,54011,2474,Florida
48,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"Less than $5,000",Total,Male,0,0,Florida
49,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$5,000,$9,000",Total,Male,287,397,Florida
50,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$10,000-$24,999",Total,Male,826,859,Florida
51,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$25,000-$49,999",Total,Male,1642,1712,Florida
52,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$50,000-$99,999",Total,Male,4022,3855,Florida
53,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$100,000-$249,999",Total,Male,12771,7608,Florida
54,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$250,000 to $499,999",Total,Male,18673,7215,Florida
55,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$500,000-$999,999",Total,Male,33055,5881,Florida
56,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$1,000,000 or more",Total,Male,306753,10569,Florida
67,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"Less than $5,000",Total,Equally male/female,0,0,Florida
68,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$5,000,$9,000",Total,Equally male/female,0,0,Florida
69,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$10,000-$24,999",Total,Equally male/female,0,0,Florida
70,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$25,000-$49,999",Total,Equally male/female,354,313,Florida
71,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$50,000-$99,999",Total,Equally male/female,1137,908,Florida
72,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$100,000-$249,999",Total,Equally male/female,5159,2027,Florida
73,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$250,000 to $499,999",Total,Equally male/female,5670,1696,Florida
74,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$500,000-$999,999",Total,Equally male/female,9192,1529,Florida
75,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$1,000,000 or more",Total,Equally male/female,46865,2350,Florida
86,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"Less than $5,000",Hispanic,Total,0,0,Florida
87,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$5,000,$9,000",Hispanic,Total,0,0,Florida
88,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$10,000-$24,999",Hispanic,Total,0,0,Florida
89,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$25,000-$49,999",Hispanic,Total,306,335,Florida
90,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$50,000-$99,999",Hispanic,Total,900,634,Florida
91,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$100,000-$249,999",Hispanic,Total,1918,1206,Florida
92,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$250,000 to $499,999",Hispanic,Total,4090,1221,Florida
93,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$500,000-$999,999",Hispanic,Total,6732,1182,Florida
94,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$1,000,000 or more",Hispanic,Total,30098,1094,Florida
107,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"Less than $5,000",Equally Hispanic/non-Hispanic,Total,0,0,Florida
108,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$5,000,$9,000",Equally Hispanic/non-Hispanic,Total,0,0,Florida
109,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$10,000-$24,999",Equally Hispanic/non-Hispanic,Total,0,0,Florida
110,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$25,000-$49,999",Equally Hispanic/non-Hispanic,Total,0,0,Florida
111,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$50,000-$99,999",Equally Hispanic/non-Hispanic,Total,0,0,Florida
112,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$100,000-$249,999",Equally Hispanic/non-Hispanic,Total,679,190,Florida
113,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$250,000 to $499,999",Equally Hispanic/non-Hispanic,Total,0,0,Florida
114,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$500,000-$999,999",Equally Hispanic/non-Hispanic,Total,0,0,Florida
115,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$1,000,000 or more",Equally Hispanic/non-Hispanic,Total,0,0,Florida
129,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"Less than $5,000",Non-Hispanic,Total,918,498,Florida
130,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$5,000,$9,000",Non-Hispanic,Total,304,506,Florida
131,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$10,000-$24,999",Non-Hispanic,Total,1149,1261,Florida
132,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$25,000-$49,999",Non-Hispanic,Total,2179,2490,Florida
133,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$50,000-$99,999",Non-Hispanic,Total,6633,5813,Florida
134,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$100,000-$249,999",Non-Hispanic,Total,21501,11554,Florida
135,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$250,000 to $499,999",Non-Hispanic,Total,29670,10073,Florida
136,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$500,000-$999,999",Non-Hispanic,Total,45859,8022,Florida
137,"Tampa-St. Petersburg-Clearwater, FL Metro Area",310M400US45300,"$1,000,000 or more",Non-Hispanic,Total,374362,14129,Florida

In [9]:
final_tampa.to_csv('../assessment_8/data/census_data_cleaned_tampa.csv', index=False)